### ISSUE TITLE
Chip select with SPI

### ISSUE THREAD

**Issue by ydrolet** [unosquare/raspberryio#86]
I am confused about the SPI channels. On RPi 3, there are 2 SPI buses, SPI0 and SPI1. With SPI0, there are 2 chip select, CE0 and CE1. Are channels referring to the different SPI buses or the different chip select? I didn't succeed to test with channel 1 because I get a **Unable to open SPI device: 1** message. However, when I choose channel 0 and I have a single chip on the bus that is wired to CE0, I get correct readings.

**Comment by k3z0** [comment]
Hi @ydrolet 

This problem is caused by the actual implementation of WiringPi library. WiringPi does only support SPI0 bus. It supposed to sopport both chip select CE0 and CE1, but we faced some problems trying to share the same bus with 2 devices, so we need to make a custom modification to the WiringPi library in order to use the bus SPI1. When you use Channel0, you are actually using CE0 from SPI0 bus and when you use Channel1 you are using CE0 from SPI1.

We are working in the implementation of PiGpio library, in theory this library could use any CE in both SPI busses. You can try our current implementation [here](https://github.com/unosquare/pigpio-dotnet).

**Comment by ydrolet** [comment]
Thanks @k3z0 ! I confirm that it is working. I was unable to use the channel 1 simply because it wasn't enabled. I just needed to add `dtoverlay=spi1-1cs` in the `/boot/config.txt` file ([found solution here](https://raspberrypi.stackexchange.com/a/56503)). For now, for our project, we will just use CE0 on SPI0 and CE0 on SPI1. Maybe later we will try your implementation with PiGpio. I suggest that the [SPI section of the README](https://github.com/unosquare/raspberryio#using-the-spi-bus) be updated to explain this issue.

**Comment by geoperez** [comment]
Done!
